---
- hosts: all
  gather_facts: yes

- name: Configuring the HAproxy loadbalancer
  hosts: HAproxy
  become: yes
  tasks:

    
    
    

    - name: Installing HAproxy
      apt:
        name: haproxy
        state: present
        update_cache: true
      

    - name: gather server ip addresses
      setup:
            filter: ansible_default_ipv4.address     
         
    
    - name: copy files haproxy.cfg
      template:
        src: haproxy.cfg.j2
        dest: "/etc/haproxy/haproxy.cfg"


    - name: restart haproxy
      service:
       name: haproxy
       state: restarted

- hosts: webservers
  become: yes
  tasks:
    - name: install pip
      apt:
        name: python3-pip
        state: present
    
    - name: install flask
      pip:
        executable: pip3
        name: flask
        state: latest

    - name: createnew directory
      file:
              path: "/home/flask-app/"
              state: directory
    - name: copy app.py to webservers
      template:
        src: "application2.py"
        dest: "/home/flask-app/app.py"


    - name: start flask app
      shell: |
        export FLASK_APP=/home/flask-app/app.py
        flask run --host=0.0.0.0 --port=80 &
