- hosts: all
  gather_facts: yes

- name: Configuring the HAproxy loadbalancer
  hosts: HAproxy
  become: yes
  tasks:
   
   - name: updating apt cache
     become: true
     apt:
       update_cache: true
   
   
   - name: Installing HAproxy
      apt:

        name: haproxy
        state: present
        update_cache: true


    - name: gather server ip addresses
      setup:
            filter: ansible_default_ipv4.address


    - name: copy files haproxy.cfg
      template:
        src: haproxy.cfg.j2
        dest: "/etc/haproxy/haproxy.cfg"


    - name: restart haproxy
      service:
       name: haproxy
       state: restarted

#configuring the webservers
- hosts: webservers
  become: yes
  tasks:
  
    - name: Updating apt cache
      become: true
      apt:
        update_cache: true
  
    - name: install pip
      apt:

        name: python3-pip
        state: present

    - name: Install Python3
      become: true
      apt:
        name: python3
        state: present

    - name: install flask
      pip:
        executable: pip3
        name: flask
        state: latest

    - name: install gunicorn
      pip:
        executable: pip3
        name: gunicorn
        state: latest


    - name: createnew directory
      file:
              path: "/home/flask-app/"
              state: directory
    - name: copy app.py to webservers
      template:
        src: application.py
        dest: "/home/flask-app/app.py"


    - name: start flask app
      shell: |
        cd /home/flask-app/
        gunicorn --bind 0.0.0.0:80 app:app& 
        
   #the above code we deployed using gunicorn ( more details in README file)
   #to use the traditional deployment please replace the above shell command by below one:
        #shell: |
        #  export FLASK_APP=/home/flask-app/app.py
        #  export FLASK_ENV=production
        #  flask run --host=0.0.0.0 --port=80 &


- hosts: webservers
  become: yes
  gather_facts: yes
                                                                                                 
